### ISSUE TITLE
NIP-0002 - Apostille Library Specification

### ISSUE THREAD

**Issue by gimyboya** [NemProject/NIP#3]
# NIP-0002 - Apostille Library Specification

## Summary

```
	NIP: ?
	* Layer:  Library
	Title: Apostille Library Specification
	Author: 
	* Discussions-To: <telegram group>
	Comments-URI: 
	Status: Draft
	Type: Standards Track
	Created: 2018-03-15
	License: BSD-2-Clause
```
## Introduction/Abstract
NEM Apostille is a standard that enables a very versatile blockchain certificate system. It is used for a variety of use cases including the following: 

1) proof of existence for real world and digital products, 
2) certificates of ownership and operation for IOT devices, 
3) use the blockchain to show chain-of-custody and/or supply chain projects
4) providing on-chain certificates, diplomas, land titles, ID where the entire certificate is represented on the blockchain and is transferable and updatable. 
5) and more...

The key innovation of Apostille is the realization that every item can be given its own private key, and that private key can be used to make a container address to record data about the item, have value sent to and from the item, and taking advantage of NEM's advanced multisig be used to even transfer ownership of the item's container on-chain from person to person.  

This is an evolutionary leap from other blockchain notarization applications which often just record a fingerprint or hash of a document to show that it exists. 

Also, due to the nature of NEM's architecture, few if any other blockchains can reproduce the utility unlocked by the NEM Apostille Standard. 

## Motivation

Apostille protocol and standards are an advanced way of using NEM blockchain for notarization purposes. and it is crucial to have a dedicated library that clearly documents the protocol and its standards with the hope of getting future contributions improving upon this standard.

## Specification

: required

The technical specification should describe the syntax and semantics of any new feature. The specification should be detailed enough to allow competing, interoperable implementations for any of the current components.

## Design Decisions

: required

Discuss design decisions (including, as examples):

- Reason about the correctness of the implementation.
- "Feel and fit" with existing core libraries.
- Performance and threading considerations.
- Potential conflicts with existing libraries, e.g. name clashes, IDE auto-import friction, etc.

The rationale fleshes out the specification by describing what motivated the design and why particular design decisions were made. It should describe alternate designs that were considered and related work. The rationale should provide evidence of consensus within the community and discuss important objections or concerns raised during the discussion.

## Implementation

[Apostill-library](https://github.com/gimyboya/Apostille-library) repository can be found here

## Drawbacks

As a second layer standard and protocol, the Apostille Library could be

1. implemented incorrectly by third-party developers.
2. could be implemented in incompatible ways.
3. more feedback from industry partners is needed to clearly define the standard.
4. the current version of NEM often requires multiple transactions spanning multiple blocks for one task (this is hoped to be addressed in catapult multi-layer multisig and aggregated transactions).

## References

White Paper: https://nem.io/wp-content/themes/nem/files/ApostilleWhitePaper.pdf
Project Site: https://nem.io/project/apostille/

## History

| **Date**   | **Version**   |
| ---------- | ------------- |
| 2018-03-15 | Initial Draft |

**Comment by aleixmorgadas** [comment]
The specification section should be the operations described in the apostille white paper somehow.

About the drawbacks:

> 1. implemented incorrectly by third-party developers. & 2. could be implemented in incompatible ways.

The NIP should contain a suit test to ensure the implementation by third-party is developed according to the specification

> 3. more feedback from industry partners is needed to clearly define the standard.

This need should help Apostille be implemented in more systems, it will reduce the feedback cycle.

> 4. the current version of NEM often requires multiple transactions spanning multiple blocks for one task (this is hoped to be addressed in catapult multi layer multisig and aggregated transactions).

We can review the NIP later, it is not an issue now.

**Comment by gimyboya** [comment]
@dgarcia360 thank you for the insights

Does this mean that NIS1 API will be depreciated and we should move forward with catapult?

**Comment by dgarcia360** [comment]
Final information regarding compatibility with current NIS1 API is not yet available. However, check hat the API sets of NIS1 API and Catapult are not compatible. 

https://nemtech.github.io/api/overview.html

Regarding Apostille Library, there are some options to assess, depending on development timings and  how soon this library will available be available on the public network: 

- Start directly with directly new NEM2-SDK:
https://nemtech.github.io/sdk/overview.html

- Start using Nem-Library for NIS1, and then migrate to NEM2-SDK having in mind the breaking changes and effort to adapt it once Catapult is released:
http://nem602.xyz/docs/sdk/release-notes/00-migration.html

**Comment by gimyboya** [comment]
closing this issue in favor of [this one](https://github.com/nemtech/NIP/issues/2)
